# Generated by Django 4.2 on 2023-05-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='folder_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
