# Generated by Django 4.2 on 2023-05-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_documents_folder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='folder_type',
            field=models.CharField(default='Certificates', max_length=255),
        ),
    ]
