# Generated by Django 4.2 on 2023-05-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_documents_folder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='folder_type',
            field=models.CharField(max_length=255),
        ),
    ]
